development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:d67f4c7ae40fc6fd4535a2743d40f176@scat.redistogo.com:11898/
  # channel_prefix: Digital_Salvage_production
